# These are supported funding model platforms

github: BuxOrg
custom: https://getbux.io/?utm_source=github&utm_medium=sponsor-link&utm_campaign=go-buxclient&utm_term=go-buxclient&utm_content=go-buxclient
